from aiogram.fsm.state import State, StatesGroup


class UserFlow(StatesGroup):
    idle = State()
    choosing_language = State()
    choosing_submission_type = State()
    uploading_file = State()
    uploading_icon_file = State()
    choosing_description_language = State()
    editing_description_translation = State()
    editing_usage_ru = State()
    editing_usage_en = State()
    choosing_category = State()
    confirming_submission = State()
    editing_draft_field = State()
    searching = State()
    entering_admin_comment = State()
    
    choosing_plugin_to_update = State()
    uploading_update_file = State()
    entering_changelog = State()
    confirming_update = State()


class AdminFlow(StatesGroup):
    menu = State()
    reviewing = State()
    editing_draft_field = State()
    editing_icon_field = State()
    entering_reject_comment = State()
    linking_author_user = State()
    editing_config = State()
    entering_broadcast = State()
    confirming_broadcast = State()
    searching_plugin = State()
    editing_catalog_plugin = State()
    editing_catalog_field = State()
    uploading_catalog_file = State()
    entering_post = State()
    confirming_post = State()
    scheduling_post = State()
    scheduling_plugin = State()
    searching_icon = State()
    linking_author_icon_user = State()
    editing_catalog_icon = State()
    editing_catalog_icon_field = State()