from aiogram.fsm.state import State, StatesGroup


class PosterFlow(StatesGroup):
    entering_channel_ref = State()
    composing_text = State()
    composing_media = State()
    composing_buttons = State()
    previewing = State()
    composing_time = State()
    entering_autodel_date = State()


class UserFlow(StatesGroup):
    idle = State()
    choosing_language = State()
    choosing_submission_type = State()
    uploading_file = State()
    entering_min_version = State()
    uploading_pending_file = State()
    choosing_description_language = State()
    editing_description_translation = State()
    editing_usage_ru = State()
    editing_usage_en = State()
    choosing_category = State()
    confirming_submission = State()
    editing_draft_field = State()
    searching = State()
    entering_admin_comment = State()
    entering_publish_not_before = State()
    entering_moderation_vote_reason = State()
    entering_joinly_chat = State()

    choosing_plugin_to_update = State()
    uploading_update_file = State()
    uploading_pending_update_file = State()
    entering_changelog = State()
    confirming_update = State()

    entering_stenka_tag = State()


class AdminFlow(StatesGroup):
    menu = State()
    reviewing = State()
    editing_draft_field = State()
    editing_icon_field = State()
    entering_reject_comment = State()
    entering_rework_comment = State()
    entering_author_message = State()
    entering_reject_template = State()
    linking_author_user = State()
    editing_config = State()
    entering_broadcast = State()
    confirming_broadcast = State()
    searching_plugin = State()
    editing_catalog_plugin = State()
    editing_catalog_field = State()
    uploading_catalog_file = State()
    entering_post = State()
    confirming_post = State()
    scheduling_post = State()
    scheduling_plugin = State()
    adding_schedule_preset = State()
    editing_scheduled_time = State()
    scheduled_post_edit_text = State()
    scheduled_post_edit_time = State()
    searching_icon = State()
    linking_author_icon_user = State()
    editing_catalog_icon = State()
    editing_catalog_icon_field = State()

    entering_sync_version = State()
    entering_sync_catalog = State()
    entering_erase_id = State()

    entering_source_username = State()
    entering_source_title = State()
    entering_source_link = State()
    attaching_source_plugin = State()
